### ISSUE TITLE
Missing lambda environment variable PATH 

### ISSUE THREAD

**Issue by jpmmota** [aws-samples/lambda-web-scraper-example#1]
After deploying the lambda function and trying to run a test, I've got the following error:

`"Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n"`

I was able to fix it by adding the PATH environment on lambda_app_stack.py file and now I am wondering if a Pull Request would be considered.

**Comment by kafka399** [comment]
Yes, please send a PR
